In [1]:
import pandas as pd

# Load the dataset
df = pd.read_csv(
    "../data/HHS_Unaccompanied_Alien_Children_Program.csv"
)

# Convert Date column
df["Date"] = pd.to_datetime(df["Date"])

# Sort by date
df = df.sort_values("Date").reset_index(drop=True)

# Display basic information
print("Dataset shape:", df.shape)
print("\nDate range:")
print(df["Date"].min(), "to", df["Date"].max())

display(df.head())

Dataset shape: (1170, 6)

Date range:
2023-01-12 00:00:00 to 2025-12-21 00:00:00

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
0,2023-01-12,33.0,53.0,34.0,"6,566",436.0
1,2023-01-22,32.0,49.0,39.0,"7,122",227.0
2,2023-01-23,32.0,50.0,39.0,"7,280",181.0
3,2023-01-24,47.0,42.0,47.0,"7,433",175.0
4,2023-01-25,20.0,22.0,41.0,"7,538",180.0

In [2]:
# Check for missing values

print("Missing values:")
print(df.isnull().sum())

Missing values:
Date                                               450
Children apprehended and placed in CBP custody*    450
Children in CBP custody                            450
Children transferred out of CBP custody            450
Children in HHS Care                               450
Children discharged from HHS Care                  450
dtype: int64

In [3]:
# Remove completely empty rows

df = df.dropna(how="all")

print("Dataset shape after removing empty rows:")
print(df.shape)

print("\nMissing values after removing empty rows:")
print(df.isnull().sum())

Dataset shape after removing empty rows:
(720, 6)

Missing values after removing empty rows:
Date                                               0
Children apprehended and placed in CBP custody*    0
Children in CBP custody                            0
Children transferred out of CBP custody            0
Children in HHS Care                               0
Children discharged from HHS Care                  0
dtype: int64

In [4]:
# Save the cleaned dataset

df.to_csv("../data/cleaned_data.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [5]:
# Check the cleaned dataset

print("Dataset shape:", df.shape)

print("\nData types:")
print(df.dtypes)

print("\nFirst 5 rows:")
display(df.head())

Dataset shape: (720, 6)

Data types:
Date                                               datetime64[us]
Children apprehended and placed in CBP custody*           float64
Children in CBP custody                                   float64
Children transferred out of CBP custody                   float64
Children in HHS Care                                          str
Children discharged from HHS Care                         float64
dtype: object

First 5 rows:

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
0,2023-01-12,33.0,53.0,34.0,"6,566",436.0
1,2023-01-22,32.0,49.0,39.0,"7,122",227.0
2,2023-01-23,32.0,50.0,39.0,"7,280",181.0
3,2023-01-24,47.0,42.0,47.0,"7,433",175.0
4,2023-01-25,20.0,22.0,41.0,"7,538",180.0

In [6]:
import os

print(os.path.exists("../data/cleaned_data.csv"))

True

In [7]:
# Sort data by date

df = df.sort_values("Date").reset_index(drop=True)

# Check the date order
print("First date:", df["Date"].min())
print("Last date:", df["Date"].max())

print("\nDataset shape:")
print(df.shape)

First date: 2023-01-12 00:00:00
Last date: 2025-12-21 00:00:00

Dataset shape:
(720, 6)

In [8]:
# Save the cleaned dataset

df.to_csv("../data/cleaned_data.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!